# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.

on:

  # Allows you to run this workflow manually from the Actions tab

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:

  # This workflow contains a single job called "build"

  buildAndroid:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout

        uses: actions/checkout@v2.3.1

      - name: Setup Android NDK

        uses: nttld/setup-ndk@v1

        id: setup-ndk

        with:

          ndk-version: r21e

      - name: Setup Java JDK

        uses: actions/setup-java@v1

        with:

          java-version: 11

      - name: Setup Android SDK

        uses: android-actions/setup-android@v2

      - name: Setup Haxe

        uses: krdlab/setup-haxe@v1.1.5

        with:

          haxe-version: 4.2.5

      - name: Install Haxelibs

        run: |

          haxelib --quiet install lime 7.9.0

          haxelib --quiet install openfl 9.1.0

          haxelib --quiet install flixel

          haxelib --quiet --never run lime setup

          haxelib --quiet install flixel-ui

          haxelib --quiet install flixel-addons

          haxelib --quiet install hscript

          haxelib --quiet install polymod

          haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools.git --quiet

      - name: Setup Lime

        run: |

          haxelib run lime setup -alias -y

          haxelib run lime config ANDROID_SDK $ANDROID_HOME

          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME

          haxelib run lime config JAVA_HOME $JAVA_HOME

          haxelib run lime config ANDROID_SETUP true

          haxelib set lime 7.9.0

          haxelib set openfl 9.1.0

          haxelib list

        env:

          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Build APK

        run: lime build android -Dnightly

      - name: Publish Artifact

        uses: actions/upload-artifact@v2.2.4

        with:

          name: androidBuild

          path: export/release/android/bin/app/build/outputs/apk/debug
